### ISSUE TITLE
Couldn't load plugin 'GSI-VTDownloader-master' due to an error when calling its classFactory() method 

### ISSUE THREAD

**Issue by biskwikman** [Kanahiro/GSI-VTDownloader#5]
インストールすれば下のメッセージが表示される：

`Couldn't load plugin 'GSI-VTDownloader-master' due to an error when calling its classFactory() method 

OSError: Could not find lib geos_c or load any of its variants ['/Applications/QGIS3.14.app/Contents/Frameworks/Python.framework/Versions/Current/lib/libgeos_c.dylib', '/Library/Frameworks/GEOS.framework/Versions/Current/GEOS', '/opt/local/lib/libgeos_c.dylib']. 
Traceback (most recent call last):
  File "/Applications/QGIS3.14.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/danielhenri/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/GSI-VTDownloader-master/__init__.py", line 35, in classFactory
    from .vtdownloader import VTDownloader
  File "/Applications/QGIS3.14.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/danielhenri/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/GSI-VTDownloader-master/vtdownloader.py", line 30, in 
    from .vtdownloader_dialog import VTDownloaderDialog
  File "/Applications/QGIS3.14.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/danielhenri/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/GSI-VTDownloader-master/vtdownloader_dialog.py", line 33, in 
    from .gsi_geojson_generator import GsiGeojsonGenerator
  File "/Applications/QGIS3.14.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/danielhenri/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/GSI-VTDownloader-master/gsi_geojson_generator.py", line 19, in 
    from .exlib import tiletanic
  File "/Applications/QGIS3.14.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/danielhenri/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/GSI-VTDownloader-master/exlib/tiletanic/__init__.py", line 2, in 
    from . import tileschemes, tilecover
  File "/Applications/QGIS3.14.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/danielhenri/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/GSI-VTDownloader-master/exlib/tiletanic/tilecover.py", line 3, in 
    from shapely import geometry, ops, prepared
  File "/Applications/QGIS3.14.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS3.14.app/Contents/MacOS/../Resources/python/shapely/geometry/__init__.py", line 4, in 
    from .base import CAP_STYLE, JOIN_STYLE
  File "/Applications/QGIS3.14.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS3.14.app/Contents/MacOS/../Resources/python/shapely/geometry/base.py", line 17, in 
    from shapely.coords import CoordinateSequence
  File "/Applications/QGIS3.14.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS3.14.app/Contents/MacOS/../Resources/python/shapely/coords.py", line 8, in 
    from shapely.geos import lgeos
  File "/Applications/QGIS3.14.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS3.14.app/Contents/MacOS/../Resources/python/shapely/geos.py", line 111, in 
    _lgeos = load_dll('geos_c', fallbacks=alt_paths)
  File "/Applications/QGIS3.14.app/Contents/MacOS/../Resources/python/shapely/geos.py", line 56, in load_dll
    libname, fallbacks or []))
OSError: Could not find lib geos_c or load any of its variants ['/Applications/QGIS3.14.app/Contents/Frameworks/Python.framework/Versions/Current/lib/libgeos_c.dylib', '/Library/Frameworks/GEOS.framework/Versions/Current/GEOS', '/opt/local/lib/libgeos_c.dylib'].

Python version: 3.7.3 (default, Mar 27 2019, 09:23:15) [Clang 10.0.1 (clang-1001.0.46.3)] 
QGIS version: 3.14.0-Pi Pi, 9f7028fd23 

Python Path:
/Applications/QGIS3.14.app/Contents/MacOS/../Resources/python
/Users/danielhenri/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/danielhenri/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS3.14.app/Contents/MacOS/../Resources/python/plugins
/Applications/QGIS3.14.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/site-packages
/Applications/QGIS3.14.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/site-packages/geos
/Applications/QGIS3.14.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python37.zip
/Applications/QGIS3.14.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7
/Applications/QGIS3.14.app/Contents/Resources/python
/Applications/QGIS3.14.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/lib-dynload
/Users/danielhenri/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/danielhenri/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/mmqgis/forms
/Users/danielhenri/Work/202007/20200706_HTO_Maps`

私はbrewでgeosもインストールしました。

**Comment by Kanahiro** [comment]
thank you for trying to use this.

'/Library/Frameworks/GEOS.framework/Versions/Current/GEOS'
please check this file exists or not.

**Comment by biskwikman** [comment]
Thanks for making it!

`Library/Frameworks/GEOS.framework` does not exist on my computer.

**Comment by Kanahiro** [comment]
https://www.kyngchaos.com/software/frameworks/
I assume GDAL complete in this page helps you.

**Comment by tomo-makes** [comment]
I faced the same error and installing GDAL complete from the above link solved this issue. Thanks!
- macOS 10.15.3
- QGIS 3.10.7
